[Round-Corners]
ActiveOuterOutlineThickness=0
ActiveOutlineAlpha=56
ActiveOutlineUseCustom=true
ActiveOutlineUsePalette=false
ActiveSecondOutlineThickness=0
DisableOutlineMaximize=false
DisableRoundFullScreen=true
DisableRoundMaximize=false
DisableRoundTile=false
InactiveCornerRadius=18
InactiveOuterOutlineThickness=0
InactiveOutlineAlpha=30
InactiveOutlineColor=255,255,255
InactiveOutlineThickness=1
InactiveOutlineUseCustom=true
InactiveOutlineUsePalette=false
InactiveSecondOutlineThickness=0
IncludeDialogs=true
IncludeNormalWindows=true
OutlineColor=255,255,255
OutlineThickness=1
Size=18

[Plugins]
kwin4_effect_shapecornersEnabled=true
