[Effect-blurplus]
BlurStrength=5
DockBlurStrength=5
BlurDocks=true
BlurMenus=true
BlurDecorations=false
BlurSaturationCompensation=true
TransparentBlur=true
Saturation=1.3
Brightness=1.0
Contrast=1.0
NoiseStrength=0
RefractionStrength=1.4
RefractionEdgeSize=24
RefractionNormalPow=2
RefractionRGBFringing=0.15
PhysicallyBasedRefraction=false
EdgeLighting=true
EdgeLightingDock=false
EdgeLightingTooltip=true
GlowColor=#B3FFFFFF
TopCornerRadius=18
BottomCornerRadius=18
MenuCornerRadius=12
DockCornerRadius=0
UseDeclaredCornerRadius=true
RoundCornersOfMaximizedWindows=true
IgnoreContentBlurRegion=false
